name: Publish on NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
        working-directory: ./front
      - run: yarn build-only
        working-directory: ./front
      - run: yarn
      - run: yarn build
      - run: mkdir build/front
      - run: cp -Rf front/dist build/front/dist
      - run: cp -Rf src/lib/locales build/main/lib/locales
      - run: cp -Rf src/lib/locales build/module/lib/locales
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
